export const LOGIN_SIMPLE_PW = "LOGIN_SIMPLE_PW";
export const CONFIRM_TEXT_MESSAGE = "CONFIRM_TEXT_MESSAGE";
export const REGISTER_ID_CARD = "REGISTER_ID_CARD";
export const REGISTER_VACCINE_PASS = "REGISTER_VACCINE_PASS";
export const REGISTER_SIMPLE_PW = "REGISTER_SIMPLE_PW";
export const CONFIRM_SIMPLE_PW = "CONFIRM_SIMPLE_PW";
export const MODIFY_SIMPLE_PW = "MODIFY_SIMPLE_PW";